[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['master']

[[redirects]]
  from = "http://onsean.robomx.com"
  to = "https://onsean.robomx.com"
  status = 301
  force = true

[[redirects]]
  from = "http://onsean.robomx.com/*"
  to = "https://onsean.robomx.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://onsean.robomx.tech"
  to = "https://onsean.robomx.tech"
  status = 301
  force = true

[[redirects]]
  from = "http://onsean.robomx.tech/*"
  to = "https://onsean.robomx.tech/:splat"
  status = 301
  force = true